// A collection of hardcoded data to be used by the App to simulate how the website would look like when we have a real database
// The methods here could be used as an interface for said database.
// Feel free to add to this if needed.

export function getProducts() {
  return [{"sectionId":11,"section":"Kolonial - Mat","id":103,"name":"Dressing"},
  {"sectionId":11,"section":"Kolonial - Mat","id":104,"name":"Smaksättning tomatbaserad"},
  {"sectionId":11,"section":"Kolonial - Mat","id":105,"name":"Senap"},
  {"sectionId":11,"section":"Kolonial - Mat","id":106,"name":"Vinäger"},
  {"sectionId":11,"section":"Kolonial - Mat","id":108,"name":"Majonnäs"},
  {"sectionId":11,"section":"Kolonial - Mat","id":111,"name":"Fisk & skaldjurskonserver"},
  {"sectionId":11,"section":"Kolonial - Mat","id":129,"name":"Pulvermos"},
  {"sectionId":11,"section":"Kolonial - Mat","id":142,"name":"Marmelad"},
  {"sectionId":11,"section":"Kolonial - Mat","id":143,"name":"Sylt & mos"},
  {"sectionId":11,"section":"Kolonial - Mat","id":150,"name":"Kaffe"},
  {"sectionId":11,"section":"Kolonial - Mat","id":155,"name":"Te"},
  {"sectionId":11,"section":"Kolonial - Mat","id":156,"name":"Chokladdryck"},
  {"sectionId":11,"section":"Kolonial - Mat","id":161,"name":"Glögg"},
  {"sectionId":11,"section":"Kolonial - Mat","id":203,"name":"Asiatiska köket"},
  {"sectionId":11,"section":"Kolonial - Mat","id":207,"name":"Mexikanska köket"},
  {"sectionId":11,"section":"Kolonial - Mat","id":208,"name":"Hela världens mat"},
  {"sectionId":11,"section":"Kolonial - Mat","id":209,"name":"Bakingredienser & dekoration"},
  {"sectionId":11,"section":"Kolonial - Mat","id":212,"name":"Sås skafferiet"},
  {"sectionId":11,"section":"Kolonial - Mat","id":219,"name":"Mjöl & mixer"},
  {"sectionId":11,"section":"Kolonial - Mat","id":223,"name":"Socker & sötning"},
  {"sectionId":11,"section":"Kolonial - Mat","id":224,"name":"Barnmat huvudmål"},
  {"sectionId":11,"section":"Kolonial - Mat","id":226,"name":"Mjölkersättning"},
  {"sectionId":11,"section":"Kolonial - Mat","id":227,"name":"Barn dryck,desserter&mellanmål"},
  {"sectionId":11,"section":"Kolonial - Mat","id":228,"name":"Barnvälling & gröt"},
  {"sectionId":11,"section":"Kolonial - Mat","id":229,"name":"Saft"},
  {"sectionId":11,"section":"Kolonial - Mat","id":233,"name":"Flingor & müsli"},
  {"sectionId":11,"section":"Kolonial - Mat","id":234,"name":"Vuxenvälling & gröt"},
  {"sectionId":11,"section":"Kolonial - Mat","id":242,"name":"Matöverkänslighet kolonial"},
  {"sectionId":11,"section":"Kolonial - Mat","id":246,"name":"Ris"},
  {"sectionId":11,"section":"Kolonial - Mat","id":247,"name":"Pasta torr"},
  {"sectionId":11,"section":"Kolonial - Mat","id":248,"name":"Pastasås"},
  {"sectionId":11,"section":"Kolonial - Mat","id":249,"name":"Matgryner"},
  {"sectionId":11,"section":"Kolonial - Mat","id":291,"name":"Färdig måltid&mixer skafferiet"},
  {"sectionId":11,"section":"Kolonial - Mat","id":514,"name":"Soppor skafferiet"},
  {"sectionId":11,"section":"Kolonial - Mat","id":253,"name":"Grönsakskonserver"},
  {"sectionId":11,"section":"Kolonial - Mat","id":254,"name":"Ärtor,bönor&gryner skafferiet"},
  {"sectionId":11,"section":"Kolonial - Mat","id":255,"name":"Efterrätter&mellanm skaffeiet"},
  {"sectionId":11,"section":"Kolonial - Mat","id":257,"name":"Torra kryddor"},
  {"sectionId":11,"section":"Kolonial - Mat","id":258,"name":"Smaksättning kryddning"},
  {"sectionId":11,"section":"Kolonial - Mat","id":259,"name":"Traditionella snacks"},
  {"sectionId":11,"section":"Kolonial - Mat","id":261,"name":"Naturella nötter,frukt&bars"},
  {"sectionId":11,"section":"Kolonial - Mat","id":262,"name":"Natursnacks"},
  {"sectionId":11,"section":"Kolonial - Mat","id":263,"name":"Olja"},
  {"sectionId":12,"section":"Konfektyr","id":158,"name":"Lösviktskonfektyr"},
  {"sectionId":12,"section":"Konfektyr","id":236,"name":"Chokladkonfektyr"},
  {"sectionId":12,"section":"Konfektyr","id":237,"name":"Konfektyr gåva"},
  {"sectionId":12,"section":"Konfektyr","id":238,"name":"Sockerkonfektyr"},
  {"sectionId":12,"section":"Konfektyr","id":239,"name":"Konfektyr stycksaker"},
  {"sectionId":12,"section":"Konfektyr","id":241,"name":"Tuggummi & halstabletter"},
  {"sectionId":13,"section":"Kolonial - Nonfood","id":120,"name":"Hund"},
  {"sectionId":13,"section":"Kolonial - Nonfood","id":121,"name":"Katt"},
  {"sectionId":13,"section":"Kolonial - Nonfood","id":122,"name":"Smådjur & övriga djur"},
  {"sectionId":13,"section":"Kolonial - Nonfood","id":154,"name":"Kaffefilter & tillbehör"},
  {"sectionId":13,"section":"Kolonial - Nonfood","id":168,"name":"Toa & Hushållspapper"},
  {"sectionId":13,"section":"Kolonial - Nonfood","id":169,"name":"Matförvaring & bakning"},
  {"sectionId":13,"section":"Kolonial - Nonfood","id":170,"name":"Diskmedel"},
  {"sectionId":13,"section":"Kolonial - Nonfood","id":171,"name":"Tvättvård"},
  {"sectionId":13,"section":"Kolonial - Nonfood","id":190,"name":"Bärkasse"},
  {"sectionId":13,"section":"Kolonial - Nonfood","id":264,"name":"Rengöringsmedel"},
  {"sectionId":13,"section":"Kolonial - Nonfood","id":267,"name":"Babyvård"},
  {"sectionId":13,"section":"Kolonial - Nonfood","id":268,"name":"Blöjor"},
  {"sectionId":14,"section":"Kroppsvård","id":175,"name":"Munvård"},
  {"sectionId":14,"section":"Kroppsvård","id":177,"name":"Deodoranter"},
  {"sectionId":14,"section":"Kroppsvård","id":181,"name":"Rakvård"},
  {"sectionId":14,"section":"Kroppsvård","id":256,"name":"Intimartiklar"},
  {"sectionId":14,"section":"Kroppsvård","id":265,"name":"Hårstyling"},
  {"sectionId":14,"section":"Kroppsvård","id":266,"name":"Hårfärg"},
  {"sectionId":14,"section":"Kroppsvård","id":269,"name":"Måltidsersättning & vikt"},
  {"sectionId":14,"section":"Kroppsvård","id":271,"name":"Sport energi & återhämtning"},
  {"sectionId":14,"section":"Kroppsvård","id":272,"name":"Hälsokost"},
  {"sectionId":14,"section":"Kroppsvård","id":273,"name":"Kosttillskott"},
  {"sectionId":14,"section":"Kroppsvård","id":274,"name":"Bomull,nässdukar,sår&fotvård"},
  {"sectionId":14,"section":"Kroppsvård","id":275,"name":"Doft"},
  {"sectionId":14,"section":"Kroppsvård","id":276,"name":"Hudvård"},
  {"sectionId":14,"section":"Kroppsvård","id":277,"name":"Allergi receptfritt"},
  {"sectionId":14,"section":"Kroppsvård","id":278,"name":"Förkylning receptfritt"},
  {"sectionId":14,"section":"Kroppsvård","id":279,"name":"Mage receptfritt"},
  {"sectionId":14,"section":"Kroppsvård","id":292,"name":"Rökavvänjning receptfritt"},
  {"sectionId":14,"section":"Kroppsvård","id":293,"name":"Värk & feber receptfritt"},
  {"sectionId":14,"section":"Kroppsvård","id":294,"name":"Bad & kosmetiska accessoarer"},
  {"sectionId":14,"section":"Kroppsvård","id":295,"name":"Make up"},
  {"sectionId":14,"section":"Kroppsvård","id":296,"name":"Tvål, bad & SPA"},
  {"sectionId":14,"section":"Kroppsvård","id":297,"name":"Hårvård"},
  {"sectionId":15,"section":"Tidningar","id":188,"name":"Tidningar"},
  {"sectionId":16,"section":"Drycker","id":166,"name":"Dryckespant försäljning"},
  {"sectionId":16,"section":"Drycker","id":651,"name":"Öl"},
  {"sectionId":16,"section":"Drycker","id":652,"name":"Läsk"},
  {"sectionId":16,"section":"Drycker","id":653,"name":"Stilldrink"},
  {"sectionId":16,"section":"Drycker","id":654,"name":"Vatten"},
  {"sectionId":16,"section":"Drycker","id":655,"name":"Energidryck"},
  {"sectionId":16,"section":"Drycker","id":656,"name":"Cider & must"},
  {"sectionId":16,"section":"Drycker","id":657,"name":"Vin & drinktillbehör"},
  {"sectionId":19,"section":"Tobak","id":184,"name":"Tobak"},
  {"sectionId":21,"section":"Hårt bröd & Kex","id":512,"name":"Söta kex & kakor"},
  {"sectionId":21,"section":"Hårt bröd & Kex","id":513,"name":"Matkex"},
  {"sectionId":21,"section":"Hårt bröd & Kex","id":576,"name":"Skorpor"},
  {"sectionId":21,"section":"Hårt bröd & Kex","id":577,"name":"Bröd hårt"},
  {"sectionId":22,"section":"Mjukt bröd","id":436,"name":"Bröd förpackat fryst"},
  {"sectionId":22,"section":"Mjukt bröd","id":504,"name":"Fikabröd mjukt kolonial"},
  {"sectionId":22,"section":"Mjukt bröd","id":505,"name":"Bröd förpackat kolonial"},
  {"sectionId":22,"section":"Mjukt bröd","id":506,"name":"Bröd förpackat"},
  {"sectionId":22,"section":"Mjukt bröd","id":622,"name":"Fikabröd mjukt"},
  {"sectionId":29,"section":"Bageri","id":280,"name":"Våg Bageri"},
  {"sectionId":29,"section":"Bageri","id":281,"name":"Bageri vete & winerbröd"},
  {"sectionId":29,"section":"Bageri","id":282,"name":"Bageri matbröd"},
  {"sectionId":29,"section":"Bageri","id":283,"name":"Bageri bitar, muffins & pajer"},
  {"sectionId":29,"section":"Bageri","id":284,"name":"Bageri"},
  {"sectionId":29,"section":"Bageri","id":285,"name":"Bageri tårtor & bakelser"},
  {"sectionId":29,"section":"Bageri","id":286,"name":"Bake off Konditori"},
  {"sectionId":29,"section":"Bageri","id":287,"name":"Bake off matbröd"},
  {"sectionId":29,"section":"Bageri","id":288,"name":"Bake off diverse"},
  {"sectionId":29,"section":"Bageri","id":289,"name":"Bake off"},
  {"sectionId":29,"section":"Bageri","id":290,"name":"Bake off färsk"},
  {"sectionId":29,"section":"Bageri","id":437,"name":"Bröd bake off fryst"},
  {"sectionId":29,"section":"Bageri","id":421,"name":"Konditori bake off fryst"},
  {"sectionId":29,"section":"Bageri","id":509,"name":"Konditori bake off kolonial"},
  {"sectionId":29,"section":"Bageri","id":574,"name":"Bröd bake off"},
  {"sectionId":31,"section":"Frukt & Grönt","id":302,"name":"Apelsiner"},
  {"sectionId":31,"section":"Frukt & Grönt","id":303,"name":"Småcitrus"},
  {"sectionId":31,"section":"Frukt & Grönt","id":317,"name":"Citron"},
  {"sectionId":31,"section":"Frukt & Grönt","id":318,"name":"Grapefrukt"},
  {"sectionId":31,"section":"Frukt & Grönt","id":319,"name":"Citrus övrigt"},
  {"sectionId":31,"section":"Frukt & Grönt","id":305,"name":"Stenfrukter"},
  {"sectionId":31,"section":"Frukt & Grönt","id":306,"name":"Vindruvor"},
  {"sectionId":31,"section":"Frukt & Grönt","id":307,"name":"Kiwi"},
  {"sectionId":31,"section":"Frukt & Grönt","id":308,"name":"Äpple"},
  {"sectionId":31,"section":"Frukt & Grönt","id":308,"name":"Äpple "},
  {"sectionId":31,"section":"Frukt & Grönt","id":309,"name":"Päron"},
  {"sectionId":31,"section":"Frukt & Grönt","id":311,"name":"Melon"},
  {"sectionId":31,"section":"Frukt & Grönt","id":312,"name":"Avocado"},
  {"sectionId":31,"section":"Frukt & Grönt","id":313,"name":"Bär"},
  {"sectionId":31,"section":"Frukt & Grönt","id":314,"name":"Ananas"},
  {"sectionId":31,"section":"Frukt & Grönt","id":321,"name":"Mango"},
  {"sectionId":31,"section":"Frukt & Grönt","id":316,"name":"Exotiskt"},
  {"sectionId":31,"section":"Frukt & Grönt","id":320,"name":"Bananer"},
  {"sectionId":31,"section":"Frukt & Grönt","id":332,"name":"Tomater"},
  {"sectionId":31,"section":"Frukt & Grönt","id":332,"name":" Tomater"},
  {"sectionId":31,"section":"Frukt & Grönt","id":333,"name":"Gurka"},
  {"sectionId":31,"section":"Frukt & Grönt","id":334,"name":"Zucchini & Aubergine"},
  {"sectionId":31,"section":"Frukt & Grönt","id":335,"name":"Blomkål"},
  {"sectionId":31,"section":"Frukt & Grönt","id":336,"name":"Broccoli"},
  {"sectionId":31,"section":"Frukt & Grönt","id":337,"name":"Sallat"},
  {"sectionId":31,"section":"Frukt & Grönt","id":338,"name":"Småblad"},
  {"sectionId":31,"section":"Frukt & Grönt","id":338,"name":"Småblad "},
  {"sectionId":31,"section":"Frukt & Grönt","id":339,"name":"Färdigskuret"},
  {"sectionId":31,"section":"Frukt & Grönt","id":341,"name":"Kål"},
  {"sectionId":31,"section":"Frukt & Grönt","id":342,"name":"Purjolök"},
  {"sectionId":31,"section":"Frukt & Grönt","id":343,"name":"Paprika"},
  {"sectionId":31,"section":"Frukt & Grönt","id":343,"name":"Paprika "},
  {"sectionId":31,"section":"Frukt & Grönt","id":344,"name":"Morötter"},
  {"sectionId":31,"section":"Frukt & Grönt","id":345,"name":"Lök"},
  {"sectionId":31,"section":"Frukt & Grönt","id":346,"name":"Färska Kryddor"},
  {"sectionId":31,"section":"Frukt & Grönt","id":347,"name":"Svamp"},
  {"sectionId":31,"section":"Frukt & Grönt","id":348,"name":"Rotfrukter"},
  {"sectionId":31,"section":"Frukt & Grönt","id":349,"name":"Ärtor & Bönor"},
  {"sectionId":31,"section":"Frukt & Grönt","id":352,"name":"Grönsaker övrigt"},
  {"sectionId":31,"section":"Frukt & Grönt","id":353,"name":"Salladsbar"},
  {"sectionId":31,"section":"Frukt & Grönt","id":354,"name":"Fruktbar"},
  {"sectionId":31,"section":"Frukt & Grönt","id":362,"name":"Potatis lösvikt"},
  {"sectionId":31,"section":"Frukt & Grönt","id":363,"name":"Potatis packad"},
  {"sectionId":32,"section":"Blommor","id":381,"name":"Snittblommor"},
  {"sectionId":32,"section":"Blommor","id":382,"name":"Arrangemang"},
  {"sectionId":32,"section":"Blommor","id":383,"name":"Blommande krukväxter"},
  {"sectionId":32,"section":"Blommor","id":384,"name":"Gröna växter"},
  {"sectionId":32,"section":"Blommor","id":385,"name":"Utplanteringsväxter"},
  {"sectionId":32,"section":"Blommor","id":386,"name":"Dekoration och butiksexponering"},
  {"sectionId":32,"section":"Blommor","id":389,"name":"Krukor, vaser & tillbehör"},
  {"sectionId":32,"section":"Blommor","id":390,"name":"Butiksmaterial & Exponering"},
  {"sectionId":41,"section":"Djupfryst","id":402,"name":"Glutenfritt fryst"},
  {"sectionId":41,"section":"Djupfryst","id":403,"name":"Bröd & desserter fryst"},
  {"sectionId":41,"section":"Djupfryst","id":404,"name":"Färdiga måltider fryst"},
  {"sectionId":41,"section":"Djupfryst","id":406,"name":"Färdiga måltider enport fryst"},
  {"sectionId":41,"section":"Djupfryst","id":408,"name":"Pizza, snacks & pirog fryst"},
  {"sectionId":41,"section":"Djupfryst","id":409,"name":"Potatis fryst"},
  {"sectionId":41,"section":"Djupfryst","id":426,"name":"Bär fryst"},
  {"sectionId":41,"section":"Djupfryst","id":427,"name":"Grönsaker fryst"},
  {"sectionId":41,"section":"Djupfryst","id":428,"name":"Fisk fryst"},
  {"sectionId":41,"section":"Djupfryst","id":429,"name":"Skaldjur fryst"},
  {"sectionId":41,"section":"Djupfryst","id":431,"name":"Glass stycksaker"},
  {"sectionId":41,"section":"Djupfryst","id":435,"name":"Glass"},
  {"sectionId":41,"section":"Djupfryst","id":422,"name":"Fågel fryst"},
  {"sectionId":41,"section":"Djupfryst","id":485,"name":"Hund fryst"},
  {"sectionId":51,"section":"Mejeri","id":575,"name":"Mejeri kolonial"},
  {"sectionId":51,"section":"Mejeri","id":580,"name":"Ägg"},
  {"sectionId":51,"section":"Mejeri","id":605,"name":"Fil"},
  {"sectionId":51,"section":"Mejeri","id":607,"name":"Mjölk"},
  {"sectionId":51,"section":"Mejeri","id":641,"name":"Yoghurt"},
  {"sectionId":51,"section":"Mejeri","id":642,"name":"Matlagning mejeri"},
  {"sectionId":51,"section":"Mejeri","id":643,"name":"Laktos&Mjölkfritt Lev Kolonial"},
  {"sectionId":51,"section":"Mejeri","id":644,"name":"Laktos & Mjölkfritt (Färsk)"},
  {"sectionId":51,"section":"Mejeri","id":646,"name":"Juice & fruktdryck kolonial"},
  {"sectionId":51,"section":"Mejeri","id":647,"name":"Juice & fruktdryck färskvaror"},
  {"sectionId":51,"section":"Mejeri","id":658,"name":"Småmål kylda"},
  {"sectionId":51,"section":"Mejeri","id":659,"name":"Matfett"},
  {"sectionId":51,"section":"Mejeri","id":669,"name":"Desserter kylda"},
  {"sectionId":61,"section":"Ost","id":635,"name":"Påläggsost  kolonial"},
  {"sectionId":61,"section":"Ost","id":665,"name":"Ost i mat"},
  {"sectionId":61,"section":"Ost","id":672,"name":"Påläggsost"},
  {"sectionId":61,"section":"Ost","id":673,"name":"Dessertost"},
  {"sectionId":70,"section":"Kött manuell","id":424,"name":"Kött manuellt fryst"},
  {"sectionId":70,"section":"Kött manuell","id":758,"name":"Kött manuellt"},
  {"sectionId":70,"section":"Kött manuell","id":759,"name":"Kött manuellt KPK"},
  {"sectionId":71,"section":"Kött","id":425,"name":"Kött fryst"},
  {"sectionId":71,"section":"Kött","id":727,"name":"Kött färs packat av butik KPK"},
  {"sectionId":71,"section":"Kött","id":728,"name":"Kött färs packat av butik"},
  {"sectionId":71,"section":"Kött","id":737,"name":"Fågel färsk packat av butik"},
  {"sectionId":71,"section":"Kött","id":738,"name":"Kött gris packat av butik KPK"},
  {"sectionId":71,"section":"Kött","id":746,"name":"Kött nöt packat av butik"},
  {"sectionId":71,"section":"Kött","id":747,"name":"Kött gris"},
  {"sectionId":71,"section":"Kött","id":748,"name":"Kött gris KPK"},
  {"sectionId":71,"section":"Kött","id":749,"name":"Kött kalv,lamm vilt&innanmat"},
  {"sectionId":71,"section":"Kött","id":753,"name":"Kött kalv,lamm,vilt&innanm KPK"},
  {"sectionId":71,"section":"Kött","id":754,"name":"Kött kalv,lamm,vilt&innanm pab"},
  {"sectionId":71,"section":"Kött","id":755,"name":"Kött pannfärdigt"},
  {"sectionId":71,"section":"Kött","id":756,"name":"Kött pannfärdigt KPK"},
  {"sectionId":71,"section":"Kött","id":757,"name":"Kött pannf packat av butik"},
  {"sectionId":71,"section":"Kött","id":763,"name":"Kött färs"},
  {"sectionId":71,"section":"Kött","id":764,"name":"Kött färs KPK"},
  {"sectionId":71,"section":"Kött","id":766,"name":"Fågel färsk"},
  {"sectionId":71,"section":"Kött","id":768,"name":"Kött nöt KPK"},
  {"sectionId":71,"section":"Kött","id":774,"name":"Kött nöt"},
  {"sectionId":71,"section":"Kött","id":776,"name":"Kött nöt packat av butik KPK"},
  {"sectionId":71,"section":"Kött","id":778,"name":"Kött gris packat av butik"},
  {"sectionId":72,"section":"Chark","id":614,"name":"Ölkorv,korvsnack&lufttork korv"},
  {"sectionId":72,"section":"Chark","id":618,"name":"Delichark"},
  {"sectionId":72,"section":"Chark","id":619,"name":"Påläggschark"},
  {"sectionId":72,"section":"Chark","id":637,"name":"Matchark"},
  {"sectionId":73,"section":"Delikatess manuell","id":612,"name":"Delichark packat av butik"},
  {"sectionId":73,"section":"Delikatess manuell","id":613,"name":"Påläggschark packat av butik"},
  {"sectionId":73,"section":"Delikatess manuell","id":616,"name":"Delichark manuell"},
  {"sectionId":73,"section":"Delikatess manuell","id":617,"name":"Påläggschark manuellt"},
  {"sectionId":73,"section":"Delikatess manuell","id":621,"name":"Matchark packat av butik"},
  {"sectionId":73,"section":"Delikatess manuell","id":636,"name":"Sallader & röror manuell"},
  {"sectionId":73,"section":"Delikatess manuell","id":662,"name":"Påläggsost packat av butik"},
  {"sectionId":73,"section":"Delikatess manuell","id":667,"name":"Matchark manuell"},
  {"sectionId":73,"section":"Delikatess manuell","id":668,"name":"Ost manuell"},
  {"sectionId":73,"section":"Delikatess manuell","id":674,"name":"Dessertost packat av butik"},
  {"sectionId":73,"section":"Delikatess manuell","id":676,"name":"Ost i mat packat av butik"},
  {"sectionId":73,"section":"Delikatess manuell","id":734,"name":"Kött butiksgrillat"},
  {"sectionId":73,"section":"Delikatess manuell","id":739,"name":"Fågel butiksgrillad"},
  {"sectionId":73,"section":"Delikatess manuell","id":767,"name":"Fågel butiksgrill pack av but"},
  {"sectionId":73,"section":"Delikatess manuell","id":777,"name":"Färdigmat manuell"},
  {"sectionId":74,"section":"Fisk manuell","id":624,"name":"Fisk&skaldjur färsk pack av bu"},
  {"sectionId":74,"section":"Fisk manuell","id":631,"name":"Fisk & skaldjur manuell"},
  {"sectionId":75,"section":"Fisk","id":502,"name":"Kaviar & fiskpastej kyld"},
  {"sectionId":75,"section":"Fisk","id":503,"name":"Fisk & skaldjur kyld"},
  {"sectionId":75,"section":"Fisk","id":623,"name":"Fisk & skaldjur färsk packat"},
  {"sectionId":75,"section":"Fisk","id":626,"name":"Fisk, rökt & gravad"},
  {"sectionId":75,"section":"Fisk","id":829,"name":"Fisk&skaldjur Konsumentpackat"},
  {"sectionId":75,"section":"Fisk","id":850,"name":"Skaldjur lake"},
  {"sectionId":76,"section":"Sallad/Färdigmat","id":153,"name":"ICA plock deli kolonial"},
  {"sectionId":76,"section":"Sallad/Färdigmat","id":423,"name":"Färdigmat manuell frys"},
  {"sectionId":76,"section":"Sallad/Färdigmat","id":453,"name":"ICA plock deli frys"},
  {"sectionId":76,"section":"Sallad/Färdigmat","id":606,"name":"Sallader & röror"},
  {"sectionId":76,"section":"Sallad/Färdigmat","id":633,"name":"Såser & smaksättning kylda"},
  {"sectionId":76,"section":"Sallad/Färdigmat","id":639,"name":"ICA plock deli färsk"},
  {"sectionId":76,"section":"Sallad/Färdigmat","id":648,"name":"Färdigmat portionsrätter"},
  {"sectionId":76,"section":"Sallad/Färdigmat","id":649,"name":"Färdigmatskomponenter"},
  {"sectionId":76,"section":"Sallad/Färdigmat","id":661,"name":"Sushikiosk"},
  {"sectionId":77,"section":"Kallskänk","id":632,"name":"Sallader & röror packat av but"},
  {"sectionId":77,"section":"Kallskänk","id":634,"name":"Såser&smaks kyld packat av but"},
  {"sectionId":77,"section":"Kallskänk","id":638,"name":"Färdigmatskomp packat av but"},
  {"sectionId":77,"section":"Kallskänk","id":733,"name":"Färdigm portionsr packa av but"},
  {"sectionId":77,"section":"Kallskänk","id":785,"name":"Catering"},
  {"sectionId":77,"section":"Kallskänk","id":816,"name":"Smörgåsar"},
  {"sectionId":77,"section":"Kallskänk","id":817,"name":"Festkök"},
  {"sectionId":77,"section":"Kallskänk","id":818,"name":"Matservice"},
  {"sectionId":77,"section":"Kallskänk","id":819,"name":"Kallskänk övrigt"},
  {"sectionId":78,"section":"Cafe/Fastfood","id":433,"name":"Glass fastfood"},
  {"sectionId":78,"section":"Cafe/Fastfood","id":797,"name":"Cafe & fastfood"},
  {"sectionId":78,"section":"Cafe/Fastfood","id":811,"name":"Cafe korvmeny"},
  {"sectionId":78,"section":"Cafe/Fastfood","id":812,"name":"Cafe Kallskänk"},
  {"sectionId":78,"section":"Cafe/Fastfood","id":813,"name":"Cafe kaffebröd"},
  {"sectionId":78,"section":"Cafe/Fastfood","id":814,"name":"Cafe drycker"},
  {"sectionId":78,"section":"Cafe/Fastfood","id":815,"name":"Fastfood övrigt"}];
}

export function getOrders() {
  return JSON.parse(localStorage.getItem("orderList"));
}

export function getOrder(i) {
  return getOrders().props.orders[i];
}

export function getCustomer() {
  return { name: "Börje", mail: "börje@mail.com", telefon: "031" };
}

export function getCustomer2() {
  return { name: "Ingjerd", mail: "Ingjerd@mail.com", telefon: "032" };
}

// section = avdelning
export function getSections() {
  return ["Konfektyr","Kolonial - Mat","Kolonial - Nonfood","Kroppsvård","Tidningar","Drycker","Tobak","Hårt bröd & Kex","Mjukt bröd","Bageri","Frukt & Grönt","Blommor","Djupfryst","Mejeri","Ost","Kött manuell","Kött","Chark","Delikatess manuell","Fisk manuell","Fisk","Sallad/Färdigmat","Kallskänk","Cafe/Fastfood"];
  
}

export function getProductGroups() {
  return [{"id":103,"name":"Dressing"},
  {"id":104,"name":"Smaksättning tomatbaserad"},
  {"id":105,"name":"Senap"},
  {"id":106,"name":"Vinäger"},
  {"id":108,"name":"Majonnäs"},
  {"id":111,"name":"Fisk & skaldjurskonserver"},
  {"id":129,"name":"Pulvermos"},
  {"id":142,"name":"Marmelad"},
  {"id":143,"name":"Sylt & mos"},
  {"id":150,"name":"Kaffe"},
  {"id":155,"name":"Te"},
  {"id":156,"name":"Chokladdryck"},
  {"id":161,"name":"Glögg"},
  {"id":203,"name":"Asiatiska köket"},
  {"id":207,"name":"Mexikanska köket"},
  {"id":208,"name":"Hela världens mat"},
  {"id":209,"name":"Bakingredienser & dekoration"},
  {"id":212,"name":"Sås skafferiet"},
  {"id":219,"name":"Mjöl & mixer"},
  {"id":223,"name":"Socker & sötning"},
  {"id":224,"name":"Barnmat huvudmål"},
  {"id":226,"name":"Mjölkersättning"},
  {"id":227,"name":"Barn dryck,desserter&mellanmål"},
  {"id":228,"name":"Barnvälling & gröt"},
  {"id":229,"name":"Saft"},
  {"id":233,"name":"Flingor & müsli"},
  {"id":234,"name":"Vuxenvälling & gröt"},
  {"id":242,"name":"Matöverkänslighet kolonial"},
  {"id":246,"name":"Ris"},
  {"id":247,"name":"Pasta torr"},
  {"id":248,"name":"Pastasås"},
  {"id":249,"name":"Matgryner"},
  {"id":291,"name":"Färdig måltid&mixer skafferiet"},
  {"id":514,"name":"Soppor skafferiet"},
  {"id":253,"name":"Grönsakskonserver"},
  {"id":254,"name":"Ärtor,bönor&gryner skafferiet"},
  {"id":255,"name":"Efterrätter&mellanm skaffeiet"},
  {"id":257,"name":"Torra kryddor"},
  {"id":258,"name":"Smaksättning kryddning"},
  {"id":259,"name":"Traditionella snacks"},
  {"id":261,"name":"Naturella nötter,frukt&bars"},
  {"id":262,"name":"Natursnacks"},
  {"id":263,"name":"Olja"},
  {"id":158,"name":"Lösviktskonfektyr"},
  {"id":236,"name":"Chokladkonfektyr"},
  {"id":237,"name":"Konfektyr gåva"},
  {"id":238,"name":"Sockerkonfektyr"},
  {"id":239,"name":"Konfektyr stycksaker"},
  {"id":241,"name":"Tuggummi & halstabletter"},
  {"id":120,"name":"Hund"},
  {"id":121,"name":"Katt"},
  {"id":122,"name":"Smådjur & övriga djur"},
  {"id":154,"name":"Kaffefilter & tillbehör"},
  {"id":168,"name":"Toa & Hushållspapper"},
  {"id":169,"name":"Matförvaring & bakning"},
  {"id":170,"name":"Diskmedel"},
  {"id":171,"name":"Tvättvård"},
  {"id":190,"name":"Bärkasse"},
  {"id":264,"name":"Rengöringsmedel"},
  {"id":267,"name":"Babyvård"},
  {"id":268,"name":"Blöjor"},
  {"id":175,"name":"Munvård"},
  {"id":177,"name":"Deodoranter"},
  {"id":181,"name":"Rakvård"},
  {"id":256,"name":"Intimartiklar"},
  {"id":265,"name":"Hårstyling"},
  {"id":266,"name":"Hårfärg"},
  {"id":269,"name":"Måltidsersättning & vikt"},
  {"id":271,"name":"Sport energi & återhämtning"},
  {"id":272,"name":"Hälsokost"},
  {"id":273,"name":"Kosttillskott"},
  {"id":274,"name":"Bomull,nässdukar,sår&fotvård"},
  {"id":275,"name":"Doft"},
  {"id":276,"name":"Hudvård"},
  {"id":277,"name":"Allergi receptfritt"},
  {"id":278,"name":"Förkylning receptfritt"},
  {"id":279,"name":"Mage receptfritt"},
  {"id":292,"name":"Rökavvänjning receptfritt"},
  {"id":293,"name":"Värk & feber receptfritt"},
  {"id":294,"name":"Bad & kosmetiska accessoarer"},
  {"id":295,"name":"Make up"},
  {"id":296,"name":"Tvål, bad & SPA"},
  {"id":297,"name":"Hårvård"},
  {"id":188,"name":"Tidningar"},
  {"id":166,"name":"Dryckespant försäljning"},
  {"id":651,"name":"Öl"},
  {"id":652,"name":"Läsk"},
  {"id":653,"name":"Stilldrink"},
  {"id":654,"name":"Vatten"},
  {"id":655,"name":"Energidryck"},
  {"id":656,"name":"Cider & must"},
  {"id":657,"name":"Vin & drinktillbehör"},
  {"id":184,"name":"Tobak"},
  {"id":512,"name":"Söta kex & kakor"},
  {"id":513,"name":"Matkex"},
  {"id":576,"name":"Skorpor"},
  {"id":577,"name":"Bröd hårt"},
  {"id":436,"name":"Bröd förpackat fryst"},
  {"id":504,"name":"Fikabröd mjukt kolonial"},
  {"id":505,"name":"Bröd förpackat kolonial"},
  {"id":506,"name":"Bröd förpackat"},
  {"id":622,"name":"Fikabröd mjukt"},
  {"id":280,"name":"Våg Bageri"},
  {"id":281,"name":"Bageri vete & winerbröd"},
  {"id":282,"name":"Bageri matbröd"},
  {"id":283,"name":"Bageri bitar, muffins & pajer"},
  {"id":284,"name":"Bageri"},
  {"id":285,"name":"Bageri tårtor & bakelser"},
  {"id":286,"name":"Bake off Konditori"},
  {"id":287,"name":"Bake off matbröd"},
  {"id":288,"name":"Bake off diverse"},
  {"id":289,"name":"Bake off"},
  {"id":290,"name":"Bake off färsk"},
  {"id":437,"name":"Bröd bake off fryst"},
  {"id":421,"name":"Konditori bake off fryst"},
  {"id":509,"name":"Konditori bake off kolonial"},
  {"id":574,"name":"Bröd bake off"},
  {"id":302,"name":"Apelsiner"},
  {"id":303,"name":"Småcitrus"},
  {"id":317,"name":"Citron"},
  {"id":318,"name":"Grapefrukt"},
  {"id":319,"name":"Citrus övrigt"},
  {"id":305,"name":"Stenfrukter"},
  {"id":306,"name":"Vindruvor"},
  {"id":307,"name":"Kiwi"},
  {"id":308,"name":"Äpple"},
  {"id":308,"name":"Äpple "},
  {"id":309,"name":"Päron"},
  {"id":311,"name":"Melon"},
  {"id":312,"name":"Avocado"},
  {"id":313,"name":"Bär"},
  {"id":314,"name":"Ananas"},
  {"id":321,"name":"Mango"},
  {"id":316,"name":"Exotiskt"},
  {"id":320,"name":"Bananer"},
  {"id":332,"name":"Tomater"},
  {"id":332,"name":" Tomater"},
  {"id":333,"name":"Gurka"},
  {"id":334,"name":"Zucchini & Aubergine"},
  {"id":335,"name":"Blomkål"},
  {"id":336,"name":"Broccoli"},
  {"id":337,"name":"Sallat"},
  {"id":338,"name":"Småblad"},
  {"id":338,"name":"Småblad "},
  {"id":339,"name":"Färdigskuret"},
  {"id":341,"name":"Kål"},
  {"id":342,"name":"Purjolök"},
  {"id":343,"name":"Paprika"},
  {"id":343,"name":"Paprika "},
  {"id":344,"name":"Morötter"},
  {"id":345,"name":"Lök"},
  {"id":346,"name":"Färska Kryddor"},
  {"id":347,"name":"Svamp"},
  {"id":348,"name":"Rotfrukter"},
  {"id":349,"name":"Ärtor & Bönor"},
  {"id":352,"name":"Grönsaker övrigt"},
  {"id":353,"name":"Salladsbar"},
  {"id":354,"name":"Fruktbar"},
  {"id":362,"name":"Potatis lösvikt"},
  {"id":363,"name":"Potatis packad"},
  {"id":381,"name":"Snittblommor"},
  {"id":382,"name":"Arrangemang"},
  {"id":383,"name":"Blommande krukväxter"},
  {"id":384,"name":"Gröna växter"},
  {"id":385,"name":"Utplanteringsväxter"},
  {"id":386,"name":"Dekoration och butiksexponering"},
  {"id":389,"name":"Krukor, vaser & tillbehör"},
  {"id":390,"name":"Butiksmaterial & Exponering"},
  {"id":402,"name":"Glutenfritt fryst"},
  {"id":403,"name":"Bröd & desserter fryst"},
  {"id":404,"name":"Färdiga måltider fryst"},
  {"id":406,"name":"Färdiga måltider enport fryst"},
  {"id":408,"name":"Pizza, snacks & pirog fryst"},
  {"id":409,"name":"Potatis fryst"},
  {"id":426,"name":"Bär fryst"},
  {"id":427,"name":"Grönsaker fryst"},
  {"id":428,"name":"Fisk fryst"},
  {"id":429,"name":"Skaldjur fryst"},
  {"id":431,"name":"Glass stycksaker"},
  {"id":435,"name":"Glass"},
  {"id":422,"name":"Fågel fryst"},
  {"id":485,"name":"Hund fryst"},
  {"id":575,"name":"Mejeri kolonial"},
  {"id":580,"name":"Ägg"},
  {"id":605,"name":"Fil"},
  {"id":607,"name":"Mjölk"},
  {"id":641,"name":"Yoghurt"},
  {"id":642,"name":"Matlagning mejeri"},
  {"id":643,"name":"Laktos&Mjölkfritt Lev Kolonial"},
  {"id":644,"name":"Laktos & Mjölkfritt (Färsk)"},
  {"id":646,"name":"Juice & fruktdryck kolonial"},
  {"id":647,"name":"Juice & fruktdryck färskvaror"},
  {"id":658,"name":"Småmål kylda"},
  {"id":659,"name":"Matfett"},
  {"id":669,"name":"Desserter kylda"},
  {"id":635,"name":"Påläggsost  kolonial"},
  {"id":665,"name":"Ost i mat"},
  {"id":672,"name":"Påläggsost"},
  {"id":673,"name":"Dessertost"},
  {"id":424,"name":"Kött manuellt fryst"},
  {"id":758,"name":"Kött manuellt"},
  {"id":759,"name":"Kött manuellt KPK"},
  {"id":425,"name":"Kött fryst"},
  {"id":727,"name":"Kött färs packat av butik KPK"},
  {"id":728,"name":"Kött färs packat av butik"},
  {"id":737,"name":"Fågel färsk packat av butik"},
  {"id":738,"name":"Kött gris packat av butik KPK"},
  {"id":746,"name":"Kött nöt packat av butik"},
  {"id":747,"name":"Kött gris"},
  {"id":748,"name":"Kött gris KPK"},
  {"id":749,"name":"Kött kalv,lamm vilt&innanmat"},
  {"id":753,"name":"Kött kalv,lamm,vilt&innanm KPK"},
  {"id":754,"name":"Kött kalv,lamm,vilt&innanm pab"},
  {"id":755,"name":"Kött pannfärdigt"},
  {"id":756,"name":"Kött pannfärdigt KPK"},
  {"id":757,"name":"Kött pannf packat av butik"},
  {"id":763,"name":"Kött färs"},
  {"id":764,"name":"Kött färs KPK"},
  {"id":766,"name":"Fågel färsk"},
  {"id":768,"name":"Kött nöt KPK"},
  {"id":774,"name":"Kött nöt"},
  {"id":776,"name":"Kött nöt packat av butik KPK"},
  {"id":778,"name":"Kött gris packat av butik"},
  {"id":614,"name":"Ölkorv,korvsnack&lufttork korv"},
  {"id":618,"name":"Delichark"},
  {"id":619,"name":"Påläggschark"},
  {"id":637,"name":"Matchark"},
  {"id":612,"name":"Delichark packat av butik"},
  {"id":613,"name":"Påläggschark packat av butik"},
  {"id":616,"name":"Delichark manuell"},
  {"id":617,"name":"Påläggschark manuellt"},
  {"id":621,"name":"Matchark packat av butik"},
  {"id":636,"name":"Sallader & röror manuell"},
  {"id":662,"name":"Påläggsost packat av butik"},
  {"id":667,"name":"Matchark manuell"},
  {"id":668,"name":"Ost manuell"},
  {"id":674,"name":"Dessertost packat av butik"},
  {"id":676,"name":"Ost i mat packat av butik"},
  {"id":734,"name":"Kött butiksgrillat"},
  {"id":739,"name":"Fågel butiksgrillad"},
  {"id":767,"name":"Fågel butiksgrill pack av but"},
  {"id":777,"name":"Färdigmat manuell"},
  {"id":624,"name":"Fisk&skaldjur färsk pack av bu"},
  {"id":631,"name":"Fisk & skaldjur manuell"},
  {"id":502,"name":"Kaviar & fiskpastej kyld"},
  {"id":503,"name":"Fisk & skaldjur kyld"},
  {"id":623,"name":"Fisk & skaldjur färsk packat"},
  {"id":626,"name":"Fisk, rökt & gravad"},
  {"id":829,"name":"Fisk&skaldjur Konsumentpackat"},
  {"id":850,"name":"Skaldjur lake"},
  {"id":153,"name":"ICA plock deli kolonial"},
  {"id":423,"name":"Färdigmat manuell frys"},
  {"id":453,"name":"ICA plock deli frys"},
  {"id":606,"name":"Sallader & röror"},
  {"id":633,"name":"Såser & smaksättning kylda"},
  {"id":639,"name":"ICA plock deli färsk"},
  {"id":648,"name":"Färdigmat portionsrätter"},
  {"id":649,"name":"Färdigmatskomponenter"},
  {"id":661,"name":"Sushikiosk"},
  {"id":632,"name":"Sallader & röror packat av but"},
  {"id":634,"name":"Såser&smaks kyld packat av but"},
  {"id":638,"name":"Färdigmatskomp packat av but"},
  {"id":733,"name":"Färdigm portionsr packa av but"},
  {"id":785,"name":"Catering"},
  {"id":816,"name":"Smörgåsar"},
  {"id":817,"name":"Festkök"},
  {"id":818,"name":"Matservice"},
  {"id":819,"name":"Kallskänk övrigt"},
  {"id":433,"name":"Glass fastfood"},
  {"id":797,"name":"Cafe & fastfood"},
  {"id":811,"name":"Cafe korvmeny"},
  {"id":812,"name":"Cafe Kallskänk"},
  {"id":813,"name":"Cafe kaffebröd"},
  {"id":814,"name":"Cafe drycker"},
  {"id":815,"name":"Fastfood övrigt"}];
}
//Innan du frågar, ja de finns två "Äpple"
